language: ruby

rvm:
  - 2.2.5

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    # DEPLOY_USER
    - secure: "cnBiB0a72KSO3A8+5lZGxmX1aIvNwa1ZWN7pP3xHXFSJUZtnYce+UxQnHw+nvIkn0try2VloFYC4n7QPgmt9ZAtxSYjEIj7vZHYi5lMFoZ7+pPLtj9XhYqdDnf2vH48I23fbm6VOducysk+Ty4vg2lKjyAAL0+gCEaXZPKBVDVZxQ0Zpw5MIBY3l4juohNAlnWD//4E1xYgnJSX9uSidJR/z1i259cF31Qg9/SzZDumMuJGSLmdMnm7peMp8IKkQfcpVcvBOwwPDSY4USkW9fSDHNCxVJKfPcgTwLpxpQOUf8cN0hhjvXi9RZBRugQ6pgUGlXNH8ZjU2ID/ytAg4prWkk1m1bOJGjCxxWFVF19t925HHqjWe62FfnijwdTBuHlQ3Csj1URoS3+ED8fqelFOmnfDZeh4W463fODMcUWQ3/MWmU/wyIk9ECTzkwisD5JzMuj+7wG1evz2xNIBo2zhFS26OIEo16h4FkffHSCTgAsKAwyPBfDPOJLyy+nmShUpECd5+NQAMMNpQ7q6DKkkQ4qyO6jjNJxVEAPsKdZxiGP+D2+R2pKSILfgV4z4Kw/hAYk/kb1bidbNAcXxGmo56eocYPxlv+T47PeS17qwFrMhug11aR0W+y3fj0I/XmZwTvzXMRsdyrWPTe62zl+Su+2WIt1KNGa2+10N3txQ="
    # DEPLOY_HOST
    - secure: "Bodfud9VNdXmWN3oFSCA7b2HAkHmN6m79CjPloLtFAXHIZWIrycyMERrOAT6MMjpPsRDU0LI24DXWW7YlxszLFjAM4D8ivML8Atmh+ZDDDlLOJaJtj/mK4kjIYp37j15Xcr9yv7nG0pt4mK6hK7K2+hZS3X85PVJHaNIRysi5Cz8vDCEygU4wDhE/u71pPXsgl+0yjg5GNOICr/ywJkbqVFrmoxUdQgVc/ACJmzKK95Ro+g1LoOP5up9BdiZmI2k8mnUbyhbiJHJRFnbqBPCPy8xCJttp4ILzxa+CtLoPAO1Y7NDBaE1SdsjZo80mW4juQKMnv8p6BX7I02IB2+v2Hezl0B+dCb+icJpHAqj+IzoMJGMpmDkdLyNfD4GOjnm5UNI1YJnpO8kDiJy0i89stK9jRJlASLR+lItpTL2lHbyiVGXIYtQmka31iosFs5B9/8f07SIR5LSHCgYe02bqKRj1UzJsw1NxJYP+HxwKfdNoSW70cCiAetfvjDvgRZsive6LjNrWACwo57kX7Id0lHgIU++fGDR1ca8l2ZyP63EfnyYmqbAo/dj+/cSTunumB0MTiHS+8ExOvzei1oGLERMQgnfRABdb7UAeivSEePafzDoNo+J4Nc22Q9mNbvcBcdJyaeNzG/U/cD4jVA3/QW6qNzA97oPxh/mYYRw88M="
    # DEPLOY_PATH
    - secure: "hG9q9dxVSNLzY2W/lrN46gctApa6tM2CBQj7gzJHfEauZh6tXgmxwZqF8NQOrBf5CqyB94Dt8D2sxQdTKIK3ntIcphLM+QM53+ezR8nex7uvDCGsJMkQE1S/UUVTpbboJl1wOEqiJkwjbKG525G0znA/iPsR5K1U7eGIwl3MSPGp22dMr0zdQnsp54NuXKYLfrj+KtlJyEiAqL+aGkbF1kHTVQylTooQsecn9cACsfuWjuoYMUMadMqQ/VsGg8+2ikKktSCIPfzkYt6am2xbcGasYYu5XkTeuPOPVQ6W5sWeY6RCR4geLfhEz/YekfdE3Deq/WhZp85cf85fU/m/ZJu+65MKMpcv+2k7QeH5zSPkxx5OBAaNCZxZZHKuAZgtpt2F+3jSHIZb62ZGw/FrZ8nZO+n+8xduz9LhjPDvWBiw/EY/y9HQRDVDGWrRPGNKm8E/AQ78zsqS7u40szuUEw3Ftxp0SichKgvehoYjXYC5OQO8x5Mtw6sQPfY1tiVGSLXUolC8Tkq4+LzanWyHjn1vW2RzS0XXcrocZ0f/r3VwLdKnx6Ekw7D7Uj0mJNJ7yxLrzJZ3cC1AxPVHkLT3xk/BPXu8QBSEzf1kA0Lp2l25Nus7jeJm+MZwiF3bfJ6vV1IOJkHjB6eXDHVf6SkJ6rjcBi8db36KSgjek7ADHLw="
    # JEKYLL_GITHUB_TOKEN
    - secure: "yabM0/dGjchiu9QHDxfWGs+Zylvh2EV21OdCjQ4KiFI/38udL3t2FRCThQ7MmxyTkWcOoAf1g70wkBuXw6pFtODzXKWPU+2PsHmcWn0F9UvYFxQV2LNMJk+433/qGxpyuBiGJ5zhNSDL4OL1TDbIZpD/MJDx71r0H8c/IE4kvMIAYpGeqibycQtdrkD8Ez0UBV1UZFNssz8uNLPSvaPtBm+I+e9bjZqZDQ9LCrsGxlDEi1W/Y+2fOpMcEP/6AqZyRwvUfKjSCDlga53b02AcF2nBag8F9ad1vWaR1GXpxsuuMmnU1VI3Xkjw6mvxvpIrtjm87qHY2oBTTb+Yzkp2rJ1s1V5b+bGZjDkfib88xE/qb/I/6rwsvn0pxJTfcI/r1xH8vmjMk6Wi06xXLtA8gKByoy1hCECSRlGfcJO2tpsO0u7RzQDoPNqgAdE9vp6vYLMDC1zKR3dS7HnV6FOhTn9qyZszmnfPhkJTmMNz0hUqYiZ5RKwuaZxc9uFP9TKav8k7pDZRGH4R8omC+2eHBudlyE8c128Nq3zyjpH+YPluIiCwJz/9Qi96FXnLm8m74LqDATvuAaNm9+3qAEZlKbOYI98ZAKFHRpM2jackqZ3DTqepdX/Yc5y83et3XMpTvFs1m9+VvrM8ZzFXZcZR3nkc7hvI7ExWJUiDlGoUrfI="

install:
  - bundle install
  - gem install html-proofer
script: env JEKYLL_ENV=production bundle exec jekyll build
#after_script: htmlproofer ./_site

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
