# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liri
email: info@liri.io
description: > # this means to ignore newlines until "baseurl:"
  An OS and apps built with modern design and features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liri.io" # the base hostname & protocol for your site
logo: "/images/logo.png"
exclude: [.travis, vendor]
social:
  links:
    - https://github.com/lirios
    - https://plus.google.com/u/0/100355783508323292342
    - https://plus.google.com/u/0/communities/115722443491803015565
    - https://www.facebook.com/Liri-935614733238741
    - https://twitter.com/liridev
google_site_verification: true
repository: lirios/lirios.github.io
github:
  repo: "https://github.com/lirios/lirios.github.io"
social_networks:
  github: lirios
  googleplus:
    page: 100355783508323292342
    community: 115722443491803015565
  twitter: liridev
  facebook: Liri-935614733238741
  youtube:

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
